import { StyleSheet } from '@react-pdf/renderer';

// Brand tokens from the Arham Always Care logo (deep red + gold on cream).
export const BRAND = {
  red: '#8B1A12',
  gold: '#C9A55C',
  goldSoft: '#E8E0D0',
  cream: '#FDFBF6',
  mat: '#F1ECE2',
  ink: '#221A14',
  muted: '#5D5347',
  soft: '#9A8D76',
};

// Activity-type rails match the app (unchanged from v1).
export const TYPE_COLOR: Record<string, string> = {
  ADMISSION: '#0E7C7B',
  TREATMENT: '#2563EB',
  ROUND: '#7C3AED',
  DIAGNOSTIC: '#0891B2',
  SURGERY: '#B5471A',
  FOOD: '#15803D',
  BATH: '#0EA5E9',
  WALK: '#A16207',
};

export const OUTCOME_BG = { 'in-care': '#93370D', discharged: '#15803D', deceased: '#B42318' } as const;

export const PAGE_PAD_TOP = 44; // room for the fixed compact header on pages 2+
export const PAGE_PAD_X = 30;

export const s = StyleSheet.create({
  page: {
    paddingTop: PAGE_PAD_TOP,
    paddingBottom: 46,
    paddingHorizontal: PAGE_PAD_X,
    fontFamily: 'Noto Sans',
    fontSize: 9,
    color: BRAND.ink,
  },
  // Page-1 masthead (in flow, fills the padding zone)
  masthead: {
    backgroundColor: BRAND.cream,
    marginHorizontal: -PAGE_PAD_X,
    marginTop: -PAGE_PAD_TOP,
    paddingTop: 18,
    paddingBottom: 12,
    paddingHorizontal: PAGE_PAD_X,
    marginBottom: 14,
    borderBottomWidth: 1.5,
    borderBottomColor: BRAND.gold,
    alignItems: 'center',
  },
  mastBrandFallback: { fontFamily: 'Noto Serif', fontWeight: 700, fontSize: 20, color: BRAND.red },
  mastKicker: { fontSize: 7, letterSpacing: 2, color: BRAND.soft, marginTop: 8 },
  // Fixed compact header, pages 2+
  pgHead: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: BRAND.cream,
    borderBottomWidth: 1,
    borderBottomColor: BRAND.gold,
    paddingHorizontal: PAGE_PAD_X,
    paddingVertical: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pgHeadMeta: { fontSize: 6.5, color: BRAND.soft, letterSpacing: 0.5 },
  hero: { flexDirection: 'row', gap: 14, marginBottom: 12 },
  heroName: { fontFamily: 'Noto Serif', fontWeight: 700, fontSize: 18, color: BRAND.red },
  pill: {
    alignSelf: 'flex-start',
    marginTop: 4,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 8,
    fontSize: 8,
    fontWeight: 700,
  },
  kv: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 },
  kvItem: { width: '50%', flexDirection: 'row', marginBottom: 3, paddingRight: 10 },
  k: { color: BRAND.soft, width: 64 },
  v: { color: BRAND.ink, fontWeight: 700, flex: 1 },
  sec: {
    fontSize: 9,
    fontWeight: 700,
    color: BRAND.red,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 12,
    marginBottom: 7,
    borderBottomWidth: 1,
    borderBottomColor: BRAND.gold,
    paddingBottom: 2,
  },
  stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 12 },
  tile: {
    borderWidth: 1,
    borderColor: BRAND.goldSoft,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 9,
    backgroundColor: BRAND.cream,
    minWidth: 78,
  },
  tileN: { fontSize: 15, fontWeight: 700, color: BRAND.red },
  tileL: { fontSize: 7, color: BRAND.soft, marginTop: 3, textTransform: 'uppercase' },
  table: { borderWidth: 1, borderColor: BRAND.goldSoft, borderRadius: 6 },
  trH: { flexDirection: 'row', backgroundColor: BRAND.cream },
  tr: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: BRAND.goldSoft },
  th: { fontSize: 7, color: BRAND.muted, textTransform: 'uppercase', padding: 5, flex: 1 },
  td: { fontSize: 8, padding: 5, flex: 1 },
  recoveryRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 12, marginBottom: 4 },
  recoveryArrow: { fontSize: 14, color: BRAND.red, fontWeight: 700, paddingBottom: 28 },
  dayBand: {
    flexDirection: 'row',
    backgroundColor: BRAND.cream,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: BRAND.goldSoft,
    paddingVertical: 5,
    paddingHorizontal: 9,
    marginTop: 14,
    marginBottom: 8,
  },
  dayLabel: { fontSize: 9, fontWeight: 700, flex: 1 },
  dayCnt: { fontSize: 8, color: BRAND.soft },
  card: {
    flexDirection: 'row',
    gap: 10,
    borderWidth: 1,
    borderColor: BRAND.goldSoft,
    borderLeftWidth: 3,
    borderRadius: 8,
    padding: 9,
    marginBottom: 7,
  },
  crow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: BRAND.goldSoft,
    borderLeftWidth: 3,
    borderRadius: 7,
    paddingVertical: 5,
    paddingHorizontal: 9,
    marginBottom: 5,
  },
  chip: { fontSize: 8, fontWeight: 700, paddingVertical: 2, paddingHorizontal: 7, borderRadius: 8 },
  time: { fontSize: 8, color: BRAND.muted, fontWeight: 700 },
  summary: { fontSize: 10, fontWeight: 700, marginTop: 5 },
  pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 5 },
  dpill: {
    fontSize: 8,
    color: BRAND.muted,
    backgroundColor: BRAND.cream,
    borderWidth: 1,
    borderColor: BRAND.goldSoft,
    borderRadius: 8,
    paddingVertical: 2,
    paddingHorizontal: 7,
  },
  dline: { fontSize: 8.5, color: BRAND.muted, marginTop: 3 },
  by: { fontSize: 7.5, color: BRAND.soft, marginTop: 6 },
  crossRef: { fontSize: 7.5, color: BRAND.red, fontWeight: 700 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 7, alignItems: 'flex-end' },
  gcap: { fontSize: 6.5, color: BRAND.soft, marginTop: 2 },
  imgMat: {
    backgroundColor: BRAND.mat,
    borderWidth: 1,
    borderColor: `${BRAND.gold}66`,
    borderRadius: 5,
    padding: 3,
    alignSelf: 'flex-start',
  },
  imgPh: {
    borderRadius: 5,
    backgroundColor: BRAND.mat,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: `${BRAND.gold}66`,
  },
  link: { fontSize: 8, color: BRAND.red, marginTop: 4 },
  sectionCard: {
    borderWidth: 1,
    borderColor: BRAND.goldSoft,
    borderLeftWidth: 3,
    borderRadius: 8,
    padding: 9,
    marginBottom: 7,
  },
  outcomeBox: { borderWidth: 1, borderRadius: 8, padding: 10, marginBottom: 18 },
  outcomeTitle: { fontSize: 10, fontWeight: 800 },
  signRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 30, paddingHorizontal: 10 },
  signCell: { alignItems: 'center' },
  signRule: { width: 150, borderTopWidth: 1, borderTopColor: BRAND.ink, marginBottom: 4 },
  signLabel: { fontSize: 7.5, color: BRAND.muted },
  provenance: { fontSize: 7, color: BRAND.soft, textAlign: 'center', marginTop: 22 },
  footer: {
    position: 'absolute',
    bottom: 18,
    left: PAGE_PAD_X,
    right: PAGE_PAD_X,
    borderTopWidth: 1,
    borderTopColor: BRAND.gold,
    paddingTop: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footText: { fontSize: 7.5, color: BRAND.soft },
});
